In [17]:
from sqlite3.dbapi2 import connect
import sqlite3
conn=sqlite3.connect("bookstore.db")
Cursor=conn.cursor()
#Book table
Cursor.execute("""CREATE TABLE IF NOT EXISTS books(book_id INTEGER PRIMARY KEY AUTOINCREMENT,
title TEXT Not Null,author TEXT Not Null,price REAL Not Null,
stock_quantity INTEGER Default 0
)""")

In [9]:
#customers table
Cursor.execute("""CREATE  TABLE IF NOT EXISTS customers(customer_id INTEGER PRIMARY KEY AUTOINCREMENT,
name TEXT Not Null,
email TEXT Unique Not Null,
city TEXT,
join_date TEXT)
""")

In [13]:
#orders table
Cursor.execute("""CREATE TABLE IF NOT EXISTS orders(
order_id INTEGER PRIMARY KEY AUTOINCREMENT,
customer_id INTEGER,
book_id INTEGER,
quantity INTEGER NOT NULL,
order_date TEXT NOT NULL,
total_amount REAL,
FOREIGN KEY(customer_id)REFERENCES customers(customer_id),
FOREIGN KEY(book_id) REFERENCES books(book_id)
)
""")
conn.commit()

In [15]:
#diplay the schema of eachntable using pragma
Cursor.execute("PRAGMA table_info(books)")
print(Cursor.fetchall())
Cursor.execute("PRAGMA table_info(customers)")
print(Cursor.fetchall())
Cursor.execute("PRAGMA table_info(orders)")
print(Cursor.fetchall())

[(0, 'book_id', 'INTEGER', 0, None, 1), (1, 'title', 'TEXT', 1, None, 0), (2, 'author', 'TEXT', 1, None, 0), (3, 'price', 'REAL', 1, None, 0), (4, 'stock_quantity', 'INTEGER', 0, '0', 0)]
[(0, 'customer_id', 'INTEGER', 0, None, 1), (1, 'name', 'TEXT', 1, None, 0), (2, 'email', 'TEXT', 1, None, 0), (3, 'city', 'TEXT', 0, None, 0), (4, 'join_date', 'TEXT', 0, None, 0)]
[(0, 'order_id', 'INTEGER', 0, None, 1), (1, 'customer_id', 'INTEGER', 0, None, 0), (2, 'book_id', 'INTEGER', 0, None, 0), (3, 'quantity', 'INTEGER', 1, None, 0), (4, 'order_date', 'TEXT', 1, None, 0), (5, 'total_amount', 'REAL', 0, None, 0)]

In [20]:
conn=sqlite3.connect("bookstore.db")
Cursor=conn.cursor()

In [22]:
#insert data
conn=sqlite3.connect("bookstore.db")
Cursor=conn.cursor()
books_data = [
('Python Programming','John Smith',599.99,25),
('Data Science Handbook','Jane Doe',899.50,15),
('Machine Learning Basics','Alan Turing',1299.00,10),
('SQL Essentials','Edgar Codd',499.99,30),
('Web Development','Tim Berners',799.00,20)
]
Cursor.executemany(
   "INSERT INTO books(title,author,price,stock_quantity) VALUES (?,?,?,?)",
books_data
)

In [23]:
customers_data = [
('Rahul Sharma','rahul@email.com','Mumbai','2024-01-15'),
('Priya Patel','priya@email.com','Delhi','2024-01-20'),
('Amit Kumar','amit@email.com','Bangalore','2024-02-01'),
('Sneha Reddy','sneha@email.com','Hyderabad','2024-02-10'),
('Vikram Singh','vikram@email.com','Mumbai','2024-02-15')
]

Cursor.executemany(
"INSERT INTO customers(name,email,city,join_date) VALUES (?,?,?,?)",
customers_data
)

In [25]:
orders_data = [
(1,1,2,'2024-03-01',1199.00),
(1,2,1,'2024-03-02',899.50),
(2,1,1,'2024-03-03',599.99),
(2,3,1,'2024-03-05',1299.00),
(3,4,3,'2024-03-07',1499.97),
(4,2,1,'2024-03-10',899.50),
(5,5,2,'2024-03-12',1598.00)
]

Cursor.executemany(
"INSERT INTO orders(customer_id,book_id,quantity,order_date,total_amount) VALUES (?,?,?,?,?)",
orders_data
)

In [26]:
conn.commit()

In [28]:
#display all records
print(Cursor.execute("SELECT * FROM books").fetchall())
print(Cursor.execute("SELECT * FROM customers").fetchall())
print(Cursor.execute("SELECT * FROM orders").fetchall())

[(1, 'Python Programming', 'John Smith', 599.99, 25), (2, 'Data Science Handbook', 'Jane Doe', 899.5, 15), (3, 'Machine Learning Basics', 'Alan Turing', 1299.0, 10), (4, 'SQL Essentials', 'Edgar Codd', 499.99, 30), (5, 'Web Development', 'Tim Berners', 799.0, 20)]
[(1, 'Rahul Sharma', 'rahul@email.com', 'Mumbai', '2024-01-15'), (2, 'Priya Patel', 'priya@email.com', 'Delhi', '2024-01-20'), (3, 'Amit Kumar', 'amit@email.com', 'Bangalore', '2024-02-01'), (4, 'Sneha Reddy', 'sneha@email.com', 'Hyderabad', '2024-02-10'), (5, 'Vikram Singh', 'vikram@email.com', 'Mumbai', '2024-02-15')]
[(1, 1, 1, 2, '2024-03-01', 1199.0), (2, 1, 2, 1, '2024-03-02', 899.5), (3, 2, 1, 1, '2024-03-03', 599.99), (4, 2, 3, 1, '2024-03-05', 1299.0), (5, 3, 4, 3, '2024-03-07', 1499.97), (6, 4, 2, 1, '2024-03-10', 899.5), (7, 5, 5, 2, '2024-03-12', 1598.0), (8, 1, 1, 2, '2024-03-01', 1199.0), (9, 1, 2, 1, '2024-03-02', 899.5), (10, 2, 1, 1, '2024-03-03', 599.99), (11, 2, 3, 1, '2024-03-05', 1299.0), (12, 3, 4, 3, '2024-03-07', 1499.97), (13, 4, 2, 1, '2024-03-10', 899.5), (14, 5, 5, 2, '2024-03-12', 1598.0)]

In [29]:
#customers from mumbai
Cursor.execute("SELECT * FROM customers WHERE city='Mumbai'")
print(Cursor.fetchall())

[(1, 'Rahul Sharma', 'rahul@email.com', 'Mumbai', '2024-01-15'), (5, 'Vikram Singh', 'vikram@email.com', 'Mumbai', '2024-02-15')]

In [30]:
#books price>800 and stock>10
Cursor.execute("SELECT * FROM books WHERE price>800 AND stock_quantity>10")
print(Cursor.fetchall())

[(2, 'Data Science Handbook', 'Jane Doe', 899.5, 15)]

In [31]:
#total orders
Cursor.execute("SELECT COUNT(*) FROM orders")
print(Cursor.fetchone())

(14,)

In [32]:
# customer who has placed the most orders (use GROUP BY and ORDER BY
Cursor.execute("""
SELECT customer_id, COUNT(*) as total_orders
FROM orders
GROUP BY customer_id
ORDER BY total_orders DESC
LIMIT 1
""")
print(Cursor.fetchall())

[(2, 4)]

In [33]:
#Calculate total revenue
Cursor.execute("SELECT SUM(total_amount) FROM orders")
print(Cursor.fetchone())

(15989.919999999998,)

In [35]:
#Task3
# pandas integration and display first 3 rows
import pandas as pd
books_df=pd.read_sql("SELECT * FROM books",conn)
customers_df=pd.read_sql("SELECT * FROM customers",conn)
orders_df=pd.read_sql("SELECT * FROM orders ",conn)
print(books_df.head(3))
print(customers_df.head(3))
print(orders_df.head(3))

   book_id                    title       author    price  stock_quantity
0        1       Python Programming   John Smith   599.99              25
1        2    Data Science Handbook     Jane Doe   899.50              15
2        3  Machine Learning Basics  Alan Turing  1299.00              10
   customer_id          name            email       city   join_date
0            1  Rahul Sharma  rahul@email.com     Mumbai  2024-01-15
1            2   Priya Patel  priya@email.com      Delhi  2024-01-20
2            3    Amit Kumar   amit@email.com  Bangalore  2024-02-01
   order_id  customer_id  book_id  quantity  order_date  total_amount
0         1            1        1         2  2024-03-01       1199.00
1         2            1        2         1  2024-03-02        899.50
2         3            2        1         1  2024-03-03        599.99

In [36]:
#merge data
report = orders_df.merge(customers_df,on="customer_id").merge(books_df,on="book_id")

report[['order_id','name','city','title','quantity','total_amount']]

,order_id,name,city,title,quantity,total_amount
0,1,Rahul Sharma,Mumbai,Python Programming,2,1199.00
1,2,Rahul Sharma,Mumbai,Data Science Handbook,1,899.50
2,3,Priya Patel,Delhi,Python Programming,1,599.99
3,4,Priya Patel,Delhi,Machine Learning Basics,1,1299.00
4,5,Amit Kumar,Bangalore,SQL Essentials,3,1499.97
5,6,Sneha Reddy,Hyderabad,Data Science Handbook,1,899.50
6,7,Vikram Singh,Mumbai,Web Development,2,1598.00
7,8,Rahul Sharma,Mumbai,Python Programming,2,1199.00
8,9,Rahul Sharma,Mumbai,Data Science Handbook,1,899.50
9,10,Priya Patel,Delhi,Python Programming,1,599.99
10,11,Priya Patel,Delhi,Machine Learning Basics,1,1299.00
11,12,Amit Kumar,Bangalore,SQL Essentials,3,1499.97
12,13,Sneha Reddy,Hyderabad,Data Science Handbook,1,899.50
13,14,Vikram Singh,Mumbai,Web Development,2,1598.00

In [37]:
#Average order value
report['total_amount'].mean()

np.float64(1142.1371428571426)

In [38]:
#most popular book
report.groupby('title')['quantity'].sum().sort_values(ascending=False)

title
Python Programming         6
SQL Essentials             6
Data Science Handbook      4
Web Development            4
Machine Learning Basics    2
Name: quantity, dtype: int64

In [39]:
conn.close()

In [41]:
#create data frame
import pandas as pd
discount_data={"book_id":[1,2,3,4,5],'discount_percent':[10,15,5,20,12]}
discount_df=pd.DataFrame(discount_data)
print(discount_df)

   book_id  discount_percent
0        1                10
1        2                15
2        3                 5
3        4                20
4        5                12

In [43]:
#save dataframe to sql table
import sqlite3
conn=sqlite3.connect("bookstore.db")
discount_df.to_sql("discounts",conn,if_exists="replace",index=False)

5

In [44]:
# verify the table ceated
query="SELECT * FROM discounts"
pd.read_sql(query,conn)

   book_id  discount_percent
0        1                10
1        2                15
2        3                 5
3        4                20
4        5                12

In [45]:
#sql join query(Books+discounts)
query = """
SELECT
b.title,
b.price,
d.discount_percent,
b.price - (b.price * d.discount_percent / 100) AS discounted_price
FROM books b
JOIN discounts d
ON b.book_id = d.book_id
"""

pd.read_sql(query, conn)

                     title    price  discount_percent  discounted_price
0       Python Programming   599.99                10           539.991
1    Data Science Handbook   899.50                15           764.575
2  Machine Learning Basics  1299.00                 5          1234.050
3           SQL Essentials   499.99                20           399.992
4          Web Development   799.00                12           703.120

In [46]:
conn.close()